spring:
  application:
    name: ADDRESS
  datasource:
    url: jdbc:mysql://localhost:3306/microservices-project
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
  
